CREATE TABLE transactions (
	id CHAR(36) NOT NULL PRIMARY KEY,
	custom_id VARCHAR(8) NOT NULL,
    time TIMESTAMP WITH TIME ZONE NOT null,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
