name: ci-nest

on:
  push:
  #  branches:
  #    - feature/IAPI-6-netverify-api-v-1-0
  #  paths:
  #    - apps/netverify/**
  #pull_request:
  #  branches:
  #    - develop
  #  paths:
  #    - apps/netverify/**      
  #workflow_dispatch:
  schedule:
    - cron: '20 21 * * 0'
  
defaults:
  run:
    working-directory: ./apps

jobs:
  Trivy-Scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    # Initializes the CodeQL tools for scanning.
   
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.

        # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
        # queries: security-extended,security-and-quality


    # Autobuild attempts to build any compiled languages  (C/C++, C#, Go, or Java).
    # If this step fails, then you should remove it and run the build manually (see below)
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    # ℹ️ Command-line programs to run using the OS shell.
    # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun

    #   If the Autobuild fails above, remove it and uncomment the following three lines.
    #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.

    # - run: |
    #     echo "Run, Build Application using script"
    #     ./location_of_script_within_repo/buildscript.sh

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"

    #- name: Run Trivy vulnerability scanner in fs mode
    #    uses: anandg112/trivy-action@feat/add-skip-dirs-option
    #    with:
    #      scan-type: 'fs'
#   #       scan-ref: '.'
    #      ignore-unfixed: true
    #      format: 'template'
    #      template: '@/contrib/sarif.tpl'
    #      output: 'trivy-results-fs.sarif'
    #      severity: 'CRITICAL'
    #      skip-dirs: "ignored-dir"
#
    #  - name: DEBUG Upload Trivy scan results to GitHub Security tab
    #    uses: github/codeql-action/upload-sarif@v1
    #    with:
    #      sarif_file: 'debug-trivy-results.sarif'
      
      