name: ci-nest

on:
  push:
  #  branches:
  #    - feature/IAPI-6-netverify-api-v-1-0
  #  paths:
  #    - apps/netverify/**
  #pull_request:
  #  branches:
  #    - develop
  #  paths:
  #    - apps/netverify/**      
  #workflow_dispatch:
  
defaults:
  run:
    working-directory: ./apps

jobs:
  Trivy-Scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in fs mode
        uses: anandg112/trivy-action@feat/add-skip-dirs-option
        with:
          scan-type: 'fs'
#          scan-ref: '.'
          ignore-unfixed: true
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-fs.sarif'
          severity: 'CRITICAL'
          skip-dirs: "ignored-dir"

      - name: DEBUG Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'debug-trivy-results.sarif'
      
      